-- MySQL Script generated by MySQL Workbench
-- Sun Apr  5 17:38:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Unigeo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Unigeo` ;

-- -----------------------------------------------------
-- Schema Unigeo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Unigeo` DEFAULT CHARACTER SET utf8 ;
USE `Unigeo` ;

-- -----------------------------------------------------
-- Table `Unigeo`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unigeo`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Unigeo`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  `apellido` VARCHAR(70) NULL,
  `tipo_documento` INT NOT NULL,
  `documento` VARCHAR(40) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `fkid_ciudad` INT NULL,
  `direccion` VARCHAR(75) NULL,
  `telefono` VARCHAR(50) NULL,
  `email` VARCHAR(100) NOT NULL,
  `estadov` INT NULL DEFAULT 1,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigeo`.`Tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unigeo`.`Tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `Unigeo`.`Tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigeo`.`Ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unigeo`.`Ciudad` ;

CREATE TABLE IF NOT EXISTS `Unigeo`.`Ciudad` (
  `id_ciudad` INT NOT NULL AUTO_INCREMENT,
  `nombre_ciudad` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id_ciudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigeo`.`Modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unigeo`.`Modulo` ;

CREATE TABLE IF NOT EXISTS `Unigeo`.`Modulo` (
  `id_modulo` INT NOT NULL AUTO_INCREMENT,
  `nombre_modulo` VARCHAR(50) NULL,
  `estadoV` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigeo`.`Permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unigeo`.`Permisos` ;

CREATE TABLE IF NOT EXISTS `Unigeo`.`Permisos` (
  `id_permisos` INT NOT NULL AUTO_INCREMENT,
  `fkid_tipo_usuario` INT NOT NULL,
  `fkid_modulo` INT NOT NULL,
  `ver` INT NULL,
  `crear` INT NULL,
  `consultar` INT NULL,
  `editar` INT NULL,
  `eliminar` INT NULL,
  `estadov` INT NULL DEFAULT 1,
  PRIMARY KEY (`id_permisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigeo`.`Universidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unigeo`.`Universidad` ;

CREATE TABLE IF NOT EXISTS `Unigeo`.`Universidad` (
  `id_universidad` INT NOT NULL AUTO_INCREMENT,
  `numero_registro` VARCHAR(100) NOT NULL,
  `nombre_universidad` VARCHAR(100) NOT NULL,
  `fkid_tipouniversidad` INT NOT NULL,
  `url_pagina` VARCHAR(200) NULL,
  `estadoV` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_universidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigeo`.`Tipo_universidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unigeo`.`Tipo_universidad` ;

CREATE TABLE IF NOT EXISTS `Unigeo`.`Tipo_universidad` (
  `id_tipo_universidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_universidad` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_tipo_universidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigeo`.`Sede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unigeo`.`Sede` ;

CREATE TABLE IF NOT EXISTS `Unigeo`.`Sede` (
  `id_sede` INT NOT NULL AUTO_INCREMENT,
  `fkid_universidad` INT NOT NULL,
  `nombre_sede` VARCHAR(100) NOT NULL,
  `fkid_ciudad` INT NULL,
  `direccion` VARCHAR(70) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(70) NULL,
  `estadoV` INT NULL DEFAULT 1,
  PRIMARY KEY (`id_sede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigeo`.`Carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unigeo`.`Carrera` ;

CREATE TABLE IF NOT EXISTS `Unigeo`.`Carrera` (
  `id_carrera` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `fkid_nivel_formacion` INT NOT NULL,
  `fkid_modalidad` INT NOT NULL,
  `tiempo` VARCHAR(50) NULL,
  `Valor` VARCHAR(70) NULL,
  `fkid_sede` INT NOT NULL,
  `fkid_snies` INT NULL,
  `estadoV` VARCHAR(45) NULL,
  PRIMARY KEY (`id_carrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigeo`.`Tipo_nivel_formacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unigeo`.`Tipo_nivel_formacion` ;

CREATE TABLE IF NOT EXISTS `Unigeo`.`Tipo_nivel_formacion` (
  `id_tipo_nivel_formacion` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_nivel_formacion` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_tipo_nivel_formacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigeo`.`Modalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unigeo`.`Modalidad` ;

CREATE TABLE IF NOT EXISTS `Unigeo`.`Modalidad` (
  `id_modalidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_modalidad` VARCHAR(70) NULL,
  PRIMARY KEY (`id_modalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigeo`.`Snies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unigeo`.`Snies` ;

CREATE TABLE IF NOT EXISTS `Unigeo`.`Snies` (
  `id_snies` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(70) NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_final` DATE NOT NULL,
  `registro_calidad` VARCHAR(70) NULL,
  PRIMARY KEY (`id_snies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigeo`.`Noticia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unigeo`.`Noticia` ;

CREATE TABLE IF NOT EXISTS `Unigeo`.`Noticia` (
  `id_noticia` INT NOT NULL AUTO_INCREMENT,
  `fecha_publicacion` DATE NULL,
  `descripcion_noticia` TEXT(300) NULL,
  `url_noticia` VARCHAR(45) NULL,
  `estadov` INT NULL DEFAULT 1,
  PRIMARY KEY (`id_noticia`))
ENGINE = InnoDB;

USE `Unigeo` ;

-- -----------------------------------------------------
-- Placeholder table for view `Unigeo`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Unigeo`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `Unigeo`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unigeo`.`view1`;
DROP VIEW IF EXISTS `Unigeo`.`view1` ;
USE `Unigeo`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
